spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_users
    username: shopwave
    password: secret
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true