server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888"  # loads api-gateway.yml from config-server

# Logging for debugging routes in dev
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG